# Generated by Django 3.2.9 on 2021-12-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_auto_20211205_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_likes',
            field=models.IntegerField(default=0),
        ),
    ]
